trigger: 
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmimage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: 'install'

    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmimage: 'ubuntu-latest'
    steps:
      - task: AzureRmWebAppDeployment@5
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'AzureConnection'
          appType: 'webAppLinux'
          WebAppName: 'NarayanaHosting'
          packageForLinux: '$(System.DefaultWorkingDirectory)/build'
          RuntimeStack: 'STATICSITE|1.0'
          DeploymentTypeLinux: 'oneDeploy'