trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '22.x'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)

- script: |
    npm install
    npm run build
  displayName: Build React App

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'build'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/react.zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop

- task: AzureWebApp@1
  inputs:
    azureSubscription: AzureConnection
    appType: webAppLinux
    appName: react-demo-webapp
    package: $(Build.ArtifactStagingDirectory)/react.zip